# Generated by Django 3.1.2 on 2023-04-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_scope_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
    ]
